// Generated by plugins/lang/cxx_status.py from Clang 23.1's clang/www/cxx_status.html: every core-language
// paper of C++29 (the plan's ML.1), and its status in that Clang. Do not edit; run the script again.
export module mcxx.plugins.lang.cpp29:table;

import std;

export namespace mcxx::plugins::lang::cpp29 {

enum class Status {
    baseline,   // Clang 23.1 implements it: the feature is gated, and -std turns it on
    partial,    // Clang 23.1 implements part of it: MC++'s Clang finishes it
    todo,       // MC++'s Clang implements it (llvm-clang-dev's lang/cpp29/<feature>)
};

struct Paper {
    std::string_view id;        // the MC1 feature id (category standard)
    std::string_view paper;     // the WG21 paper that adopted it
    std::string_view title;     // as the status page names it
    Status status;
    std::string_view clang;     // the status page's own words
};

inline constexpr std::array<Paper, 17> PAPERS { {
    { "c++29:floating-point-overflow", "P3899R3", "Clarify the behavior of floating-point overflow", Status::todo, "No" },
    { "c++29:defaulting-postfix-increment-decrement", "P3668R4", "Defaulting postfix increment and decrement operations", Status::todo, "No" },
    { "c++29:defaulted-assignment-restrictions", "P2953R5", "Adding restrictions to defaulted assignment operator functions", Status::todo, "No" },
    { "c++29:nondeterministic-pointer-provenance", "P2434R5", "Nondeterministic pointer provenance", Status::todo, "No" },
    { "c++29:invalid-pointer-operations", "P3347R6", "Invalid pointer operations", Status::todo, "No" },
    { "c++29:unicode-identifier-recommendations", "P3658R1", "Adjust identifier following new Unicode recommendations", Status::todo, "No" },
    { "c++29:return-value-and-return-void", "P3950R1", "return_value & return_void are not mutually exclusive", Status::todo, "No" },
    { "c++29:more-named-universal-character-escapes", "P3733R1", "More named universal character escapes", Status::baseline, "Clang 23" },
    { "c++29:lexical-order-lambdas", "P3847R1", "Lexical order for lambdas", Status::baseline, "Clang 3.1" },
    { "c++29:language-linkage-templates", "P2243R0", "Language linkage for templates", Status::todo, "No" },
    { "c++29:throwing-deallocation-functions-ill-formed", "P3424R2", "Deallocation functions with throwing exception specification are ill-formed", Status::todo, "No" },
    { "c++29:conditional-noexcept-specifiers-compound-requirements", "P3822R2", "Conditional noexcept specifiers in compound requirements", Status::todo, "No" },
    { "c++29:contracts-virtual-functions", "P3097R3", "Contracts for C++: virtual functions", Status::todo, "No" },
    { "c++29:consteval-only-values", "P4101R1", "Consteval-only values for C++26", Status::todo, "No" },
    { "c++29:pointer-lifetime-end-zap-proposed-solutions", "P2414R12", "Pointer lifetime-end zap proposed solutions", Status::todo, "No" },
    { "c++29:pack-indexing-template-names", "P3670R4", "Pack indexing for template names", Status::todo, "No" },
    { "c++29:embed-offset-parameter", "P3540R3", "#embed offset parameter", Status::todo, "No" },
} };

} // namespace mcxx::plugins::lang::cpp29
