module;

#include <llvm/Support/InitLLVM.h>
#include <llvm/Support/LLVMDriver.h>

// clang's own main is generated by CMake from llvm-driver-template.cpp.in; this is that call.
int clang_main(int argc, char** argv, const llvm::ToolContext&);

extern "C" {
void LLVMInitializeX86TargetInfo();
void LLVMInitializeX86Target();
void LLVMInitializeX86TargetMC();
void LLVMInitializeX86AsmPrinter();
void LLVMInitializeX86AsmParser();
void LLVMInitializeAArch64TargetInfo();
void LLVMInitializeAArch64Target();
void LLVMInitializeAArch64TargetMC();
void LLVMInitializeAArch64AsmPrinter();
void LLVMInitializeAArch64AsmParser();
}

module mcxx.backend.clang.compiler;

import std;

namespace mcxx::backend::clang::compiler {

namespace {

// llvm.codegen-dev's back ends; llvm/Config/Targets.def is empty in these packages, so cc1's
// InitializeAllTargets() registers none of them itself.
void register_targets() {
    static const bool once { [] {
        LLVMInitializeX86TargetInfo();
        LLVMInitializeX86Target();
        LLVMInitializeX86TargetMC();
        LLVMInitializeX86AsmPrinter();
        LLVMInitializeX86AsmParser();
        LLVMInitializeAArch64TargetInfo();
        LLVMInitializeAArch64Target();
        LLVMInitializeAArch64TargetMC();
        LLVMInitializeAArch64AsmPrinter();
        LLVMInitializeAArch64AsmParser();
        return true;
    }() };
    (void)once;
}

} // namespace

int run(int argc, char** argv) {
    llvm::InitLLVM init { argc, argv };
    register_targets();
    return clang_main(argc, argv, { argv[0], nullptr, false });
}

int run_as(std::string_view mode, const char* self, std::vector<std::string> args) {
    std::vector<std::string> storage;
    storage.reserve(args.size() + 1);
    const std::string_view path { self };
    const auto slash = path.find_last_of('/');
    storage.push_back(std::string { slash == std::string_view::npos ? std::string_view {} : path.substr(0, slash + 1) } + std::string { mode });
    for (auto& a : args) storage.push_back(std::move(a));
    std::vector<char*> argv;
    for (auto& s : storage) argv.push_back(s.data());
    argv.push_back(nullptr);
    int argc { static_cast<int>(storage.size()) };
    char** data { argv.data() };
    llvm::InitLLVM init { argc, data };
    register_targets();
    // argv[0] names the mode; the ToolContext carries the real path, for re-invoking itself.
    return clang_main(argc, data, { self, nullptr, false });
}

std::string_view mode_for_name(std::string_view name) {
    if (name.ends_with(".exe")) name.remove_suffix(4);
    if (name == "clang++" || name == "c++" || name == "g++" || name.starts_with("clang++-")) return "clang++";
    if (name == "clang" || name == "cc" || name == "gcc" || name.starts_with("clang-")) return "clang";
    return {};
}

std::string_view clang_version() { return "23.1.0"; }

} // namespace mcxx::backend::clang::compiler
