module;

#include <llvm/Support/InitLLVM.h>
#include <llvm/Support/LLVMDriver.h>

// clang's own main is generated by CMake from llvm-driver-template.cpp.in; this is that call.
int clang_main(int argc, char** argv, const llvm::ToolContext&);

extern "C" {
void LLVMInitializeX86TargetInfo();
void LLVMInitializeX86Target();
void LLVMInitializeX86TargetMC();
void LLVMInitializeX86AsmPrinter();
void LLVMInitializeX86AsmParser();
void LLVMInitializeAArch64TargetInfo();
void LLVMInitializeAArch64Target();
void LLVMInitializeAArch64TargetMC();
void LLVMInitializeAArch64AsmPrinter();
void LLVMInitializeAArch64AsmParser();
}

module mcxx.backend.clang.compiler;

import std;

namespace mcxx::backend::clang::compiler {

namespace {

// llvm.codegen-dev's back ends; llvm/Config/Targets.def is empty in these packages, so cc1's
// InitializeAllTargets() registers none of them itself.
void register_targets() {
    static const bool once { [] {
        LLVMInitializeX86TargetInfo();
        LLVMInitializeX86Target();
        LLVMInitializeX86TargetMC();
        LLVMInitializeX86AsmPrinter();
        LLVMInitializeX86AsmParser();
        LLVMInitializeAArch64TargetInfo();
        LLVMInitializeAArch64Target();
        LLVMInitializeAArch64TargetMC();
        LLVMInitializeAArch64AsmPrinter();
        LLVMInitializeAArch64AsmParser();
        return true;
    }() };
    (void)once;
}

// An absolute path with a drive (C:\...\clang++.exe), as a build tool starts a compiler on Windows.
// LLVM there is built as for Linux: it finds its own path from /proc/self/exe, which openkal's Windows
// target has not, or by resolving argv[0], which a drive path defeats (realpath takes it for a relative
// one). clang's driver was then left with no directory, and found neither its configuration files --
// the payload's --target: mcpp took the toolchain for x86_64-w64-windows-gnu, not MSVC's triple -- nor
// its resource directory. Such a path is the program's as given, and -no-canonical-prefixes has the
// driver take it so. Not for cc1 (argv[1] names it), nor when the command says either way itself.
bool takes_path_as_given(std::string_view self, const std::vector<std::string_view>& args) {
    const bool drive { self.size() > 2 && ((self[0] >= 'A' && self[0] <= 'Z') || (self[0] >= 'a' && self[0] <= 'z')) && self[1] == ':'
                       && (self[2] == '\\' || self[2] == '/') };
    if (!drive || (!args.empty() && args.front().starts_with("-cc1"))) return false;
    return std::ranges::none_of(args, [](std::string_view a) { return a == "-canonical-prefixes" || a == "-no-canonical-prefixes"; });
}

char no_canonical_prefixes[] { "-no-canonical-prefixes" };

} // namespace

int run(int argc, char** argv) {
    llvm::InitLLVM init { argc, argv };
    register_targets();
    std::vector<char*> args { argv, argv + argc };
    if (argc > 0 && takes_path_as_given(argv[0], { argv + 1, argv + argc })) args.insert(args.begin() + 1, no_canonical_prefixes);
    args.push_back(nullptr);
    return clang_main(static_cast<int>(args.size()) - 1, args.data(), { argv[0], nullptr, false });
}

int run_as(std::string_view mode, const char* self, std::vector<std::string> args) {
    std::vector<std::string> storage;
    storage.reserve(args.size() + 1);
    const std::string_view path { self };
    const auto slash = path.find_last_of("/\\");
    storage.push_back(std::string { slash == std::string_view::npos ? std::string_view {} : path.substr(0, slash + 1) } + std::string { mode });
    if (takes_path_as_given(path, { args.begin(), args.end() })) storage.emplace_back(no_canonical_prefixes);
    for (auto& a : args) storage.push_back(std::move(a));
    std::vector<char*> argv;
    for (auto& s : storage) argv.push_back(s.data());
    argv.push_back(nullptr);
    int argc { static_cast<int>(storage.size()) };
    char** data { argv.data() };
    llvm::InitLLVM init { argc, data };
    register_targets();
    // argv[0] names the mode; the ToolContext carries the real path, for re-invoking itself.
    return clang_main(argc, data, { self, nullptr, false });
}

std::string_view mode_for_name(std::string_view name) {
    if (name.ends_with(".exe")) name.remove_suffix(4);
    if (name == "clang++" || name == "c++" || name == "g++" || name.starts_with("clang++-")) return "clang++";
    if (name == "clang" || name == "cc" || name == "gcc" || name.starts_with("clang-")) return "clang";
    return {};
}

std::string_view clang_version() { return "23.1.0"; }

} // namespace mcxx::backend::clang::compiler
