#!/usr/bin/env python3
"""The feature tables of plugins/lang (the plan's milestone ML, its list ML.1): each core-language paper
of C++26 and C++29, from the Clang release's own status page, written as a module partition.

    python3 plugins/lang/cxx_status.py CXX_STATUS_HTML

CXX_STATUS_HTML is clang/www/cxx_status.html of the Clang MC++ builds on (llvm.clang-dev's source,
.deps/src/llvm-project-23.1.0.src/...). Writes plugins/lang/cpp26/src/table.cppm and
plugins/lang/cpp29/src/table.cppm. A feature's id is c++26:<words of its title> (or a name below,
for a paper that shares a row group's title); its status in that Clang: baseline (implemented),
partial, todo. Run again when WG21 adopts papers and the page follows.
"""
import html
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

# Papers whose title in the page is only a row group's (Reflection, Erroneous behaviour) or too long.
NAMES = {
    "P2996": "reflection",
    "P3394": "annotations-for-reflection",
    "P3293": "splicing-base-class-subobjects",
    "P3491": "define-static-objects",
    "P3096": "function-parameter-reflection",
    "P3598": "reflection-p3598",
    "P3684": "erroneous-behaviour-p3684",
    "P2573": "delete-with-reason",
    "P1967": "embed",
    "P2900": "contracts",
    "P1854": "non-encodable-string-literals-ill-formed",
    "P2558": "basic-character-set-additions",
    "P3034": "module-declarations-not-macros",
    "P3144": "delete-incomplete-type-ill-formed",
    "P2865": "remove-deprecated-array-comparisons",
    "P4004": "partial-ordering-variadic-templates",
    "P4136": "line-directive-existing-practice",
    "P3899": "floating-point-overflow",
    "P3668": "defaulting-postfix-increment-decrement",
    "P2953": "defaulted-assignment-restrictions",
    "P3658": "unicode-identifier-recommendations",
    "P3950": "return-value-and-return-void",
    "P3424": "throwing-deallocation-functions-ill-formed",
    "P3097": "contracts-virtual-functions",
    "P4101": "consteval-only-values",
}
SKIP = {"a", "an", "the", "of", "for", "to", "from", "in", "and", "be", "should", "are", "is", "with", "on"}


def text(cell):
    return html.unescape(re.sub(r"<[^>]+>", "", cell)).strip()


def kebab(title, limit=6):
    words = [w for w in re.findall(r"[a-z0-9]+", title.lower()) if w not in SKIP]
    return "-".join(words[:limit])


def rows(page, anchor):
    start = page.index(f'id="{anchor}"')
    table = page[page.index("<table", start):page.index("</table>", start)]
    out, group = [], None
    for row in re.findall(r"<tr>(.*?)</tr>", table, re.S):
        cells = re.findall(r"<td([^>]*)>(.*?)</td>", row, re.S)
        if not cells:
            continue
        if len(cells) >= 3 or (len(cells) == 2 and group is None):
            attrs, title = cells[0]
            group = (text(title), int(re.search(r'rowspan="?(\d+)', attrs).group(1)) if "rowspan" in attrs else 1)
            paper_cell, status_cell = cells[1], cells[-1]
        else:   # a later row of a group: its paper and status
            paper_cell, status_cell = cells[0], cells[-1]
        paper = re.search(r"P\d+R\d+", paper_cell[1])
        if paper is None:
            continue
        status_text = text(status_cell[1])
        cls = re.search(r'class="(\w+)"', status_cell[0])
        cls = cls.group(1) if cls else ""
        if cls == "partial" or "Partial" in status_text:
            status = "partial"
        elif cls in ("full", "unreleased") or status_text.startswith(("Clang", "Yes")):
            status = "baseline"
        else:
            status = "todo"
        out.append((group[0], paper.group(0), status, " ".join(status_text.split())))
    return out


def table(generation, entries):
    seen, lines = set(), []
    for title, paper, status, clang in entries:
        number = re.match(r"P\d+", paper).group(0)
        name = NAMES.get(number) or kebab(title)
        if name in seen:
            name = f"{name}-{number.lower()}"
        seen.add(name)
        # A paper in a row group (Reflection's, Erroneous behaviour's) is the group's title and its own number.
        grouped = sum(1 for t, *_ in entries if t == title) > 1
        summary = f"{title}: {paper}" if grouped else title
        lines.append(f'    {{ "c++{generation}:{name}", "{paper}", "{summary.replace(chr(34), chr(39))}", Status::{status}, "{clang}" }},')
    return f"""// Generated by plugins/lang/cxx_status.py from Clang 23.1's clang/www/cxx_status.html: every core-language
// paper of C++{generation} (the plan's ML.1), and its status in that Clang. Do not edit; run the script again.
export module mcxx.plugins.lang.cpp{generation}:table;

import std;

export namespace mcxx::plugins::lang::cpp{generation} {{

enum class Status {{
    baseline,   // Clang 23.1 implements it: the feature is gated, and -std turns it on
    partial,    // Clang 23.1 implements part of it: MC++'s Clang finishes it
    todo,       // MC++'s Clang implements it (llvm-clang-dev's lang/cpp{generation}/<feature>)
}};

struct Paper {{
    std::string_view id;        // the MC1 feature id (category standard)
    std::string_view paper;     // the WG21 paper that adopted it
    std::string_view title;     // as the status page names it
    Status status;
    std::string_view clang;     // the status page's own words
}};

inline constexpr std::array<Paper, {len(entries)}> PAPERS {{ {{
{chr(10).join(lines)}
}} }};

}} // namespace mcxx::plugins::lang::cpp{generation}
"""


def main():
    page = pathlib.Path(sys.argv[1]).read_text()
    for generation, anchor in (("26", "cxx26"), ("29", "cxx29")):
        entries = rows(page, anchor)
        out = HERE / f"cpp{generation}" / "src" / "table.cppm"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(table(generation, entries))
        counts = {s: sum(1 for e in entries if e[2] == s) for s in ("baseline", "partial", "todo")}
        print(f"C++{generation}: {len(entries)} papers {counts} -> {out.relative_to(HERE.parent.parent)}")


if __name__ == "__main__":
    main()
