// Generated by plugins/lang/cxx_status.py from Clang 23.1's clang/www/cxx_status.html: every core-language
// paper of C++26 (the plan's ML.1), and its status in that Clang. Do not edit; run the script again.
export module mcxx.plugins.lang.cpp26:table;

import std;

export namespace mcxx::plugins::lang::cpp26 {

enum class Status {
    baseline,   // Clang 23.1 implements it: the feature is gated, and -std turns it on
    partial,    // Clang 23.1 implements part of it: MC++'s Clang finishes it
    todo,       // MC++'s Clang implements it (llvm-clang-dev's lang/cpp26/<feature>)
};

struct Paper {
    std::string_view id;        // the MC1 feature id (category standard)
    std::string_view paper;     // the WG21 paper that adopted it
    std::string_view title;     // as the status page names it
    Status status;
    std::string_view clang;     // the status page's own words
};

inline constexpr std::array<Paper, 54> PAPERS { {
    { "c++26:remove-undefined-behavior-lexing", "P2621R2", "Remove undefined behavior from lexing", Status::baseline, "Clang 3.3" },
    { "c++26:non-encodable-string-literals-ill-formed", "P1854R4", "Making non-encodable string literals ill-formed", Status::baseline, "Clang 14" },
    { "c++26:unevaluated-strings", "P2361R6", "Unevaluated strings", Status::baseline, "Clang 18" },
    { "c++26:basic-character-set-additions", "P2558R2", "Add @, $, and ` to the basic character set", Status::baseline, "Yes" },
    { "c++26:constexpr-cast-void", "P2738R1", "constexpr cast from void*", Status::baseline, "Clang 17" },
    { "c++26:ignorability-standard-attributes", "P2552R3", "On the ignorability of standard attributes", Status::baseline, "Yes" },
    { "c++26:static-storage-braced-initializers", "P2752R3", "Static storage for braced initializers", Status::todo, "No" },
    { "c++26:user-generated-static-assert-messages", "P2741R3", "User-generated static_assert messages", Status::baseline, "Clang 17" },
    { "c++26:placeholder-variables-no-name", "P2169R4", "Placeholder variables with no name", Status::baseline, "Clang 18" },
    { "c++26:template-parameter-initialization", "P2308R1", "Template parameter initialization", Status::baseline, "Clang 18" },
    { "c++26:pack-indexing", "P2662R3", "Pack Indexing", Status::baseline, "Clang 19" },
    { "c++26:remove-deprecated-arithmetic-conversion-enumerations", "P2864R2", "Remove Deprecated Arithmetic Conversion on Enumerations", Status::baseline, "Clang 18" },
    { "c++26:disallow-binding-returned-glvalue-temporary", "P2748R5", "Disallow Binding a Returned Glvalue to a Temporary", Status::baseline, "Clang 19" },
    { "c++26:clarifying-rules-brace-elision-aggregate-initialization", "P3106R1", "Clarifying rules for brace elision in aggregate initialization", Status::baseline, "Clang 17" },
    { "c++26:attributes-structured-bindings", "P0609R3", "Attributes for Structured Bindings", Status::baseline, "Clang 19" },
    { "c++26:module-declarations-not-macros", "P3034R1", "Module Declarations Shouldn’t be Macros", Status::baseline, "Clang 23" },
    { "c++26:trivial-infinite-loops-not-undefined-behavior", "P2809R3", "Trivial infinite loops are not Undefined Behavior", Status::baseline, "Clang 19" },
    { "c++26:erroneous-behaviour-uninitialized-reads", "P2795R5", "Erroneous behaviour for uninitialized reads: P2795R5", Status::todo, "No" },
    { "c++26:erroneous-behaviour-p3684", "P3684R1", "Erroneous behaviour for uninitialized reads: P3684R1", Status::todo, "No" },
    { "c++26:delete-with-reason", "P2573R2", "= delete('should have a reason');", Status::baseline, "Clang 19" },
    { "c++26:variadic-friends", "P2893R3", "Variadic friends", Status::baseline, "Clang 20" },
    { "c++26:constexpr-placement-new", "P2747R2", "constexpr placement new", Status::baseline, "Clang 20" },
    { "c++26:delete-incomplete-type-ill-formed", "P3144R2", "Deleting a Pointer to an Incomplete Type Should be Ill-formed", Status::baseline, "Clang 19" },
    { "c++26:ordering-constraints-involving-fold-expressions", "P2963R3", "Ordering of constraints involving fold expressions", Status::baseline, "Clang 19" },
    { "c++26:structured-binding-declaration-as-condition", "P0963R3", "Structured binding declaration as a condition", Status::baseline, "Clang 21" },
    { "c++26:constexpr-structured-bindings", "P2686R5", "constexpr structured bindings", Status::todo, "No" },
    { "c++26:allowing-exception-throwing-constant-evaluation", "P3068R6", "Allowing exception throwing in constant-evaluation", Status::todo, "No" },
    { "c++26:remove-deprecated-array-comparisons", "P2865R6", "Remove Deprecated Array Comparisons from C++26", Status::baseline, "Clang 20" },
    { "c++26:structured-bindings-can-introduce-pack", "P1061R10", "Structured Bindings can introduce a Pack", Status::baseline, "Clang 21" },
    { "c++26:oxford-variadic-comma", "P3176R1", "The Oxford variadic comma", Status::baseline, "Clang 20" },
    { "c++26:trivial-unions", "P3074R7", "Trivial unions", Status::todo, "No" },
    { "c++26:partial-program-correctness", "P1494R5", "Partial program correctness", Status::todo, "No" },
    { "c++26:contracts", "P2900R14", "Contracts", Status::todo, "No" },
    { "c++26:defang-deprecate-memory-order-consume", "P3475R2", "Defang and deprecate memory_order::consume", Status::todo, "No" },
    { "c++26:concept-variable-template-template-parameters", "P2841R7", "Concept and variable-template template-parameters", Status::todo, "No" },
    { "c++26:embed", "P1967R14", "#embed", Status::todo, "No" },
    { "c++26:reflection", "P2996R13", "Reflection: P2996R13", Status::todo, "No" },
    { "c++26:annotations-for-reflection", "P3394R4", "Reflection: P3394R4", Status::todo, "No" },
    { "c++26:splicing-base-class-subobjects", "P3293R3", "Reflection: P3293R3", Status::todo, "No" },
    { "c++26:define-static-objects", "P3491R3", "Reflection: P3491R3", Status::todo, "No" },
    { "c++26:function-parameter-reflection", "P3096R12", "Reflection: P3096R12", Status::todo, "No" },
    { "c++26:reflection-p3598", "P3598R0", "Reflection: P3598R0", Status::todo, "No" },
    { "c++26:attaching-main-global-module", "P3618R0", "Attaching main to the global module", Status::baseline, "Clang 21" },
    { "c++26:expansion-statements", "P1306R5", "Expansion Statements", Status::partial, "Clang 23 (Partial) Iterating expansion statements currently cannot be expanded and will result in a diagnostic, but other types of expansion statements work." },
    { "c++26:constexpr-virtual-inheritance", "P3533R2", "constexpr virtual inheritance", Status::todo, "No" },
    { "c++26:preprocessing-never-undefined", "P2843R3", "Preprocessing is never undefined", Status::todo, "No" },
    { "c++26:allow-line-before-module-declarations", "P3868R1", "Allow #line before module declarations", Status::baseline, "Clang 21" },
    { "c++26:line-directive-existing-practice", "P4136R2", "#line is not in line with existing implementation", Status::baseline, "Yes" },
    { "c++26:partial-ordering-variadic-templates", "P4004R1", "Reconsider CWG 1395 'Partial ordering of variadic templates reconsidered'", Status::todo, "No" },
    { "c++26:ctad-type-template-template-parameters", "P3865R3", "CTAD for type template template parameters", Status::todo, "No" },
    { "c++26:adjustments-union-lifetime-rules", "P3726R2", "Adjustments to Union Lifetime Rules", Status::todo, "No" },
    { "c++26:constant-evaluations-fixes", "P4143R0", "Constant evaluations fixes", Status::todo, "No" },
    { "c++26:define-immediate-context", "P4149R1", "Define 'immediate context'", Status::todo, "No" },
    { "c++26:clarification-placement-new-deallocation", "P3769R1", "Clarification of placement new deallocation", Status::todo, "No" },
} };

} // namespace mcxx::plugins::lang::cpp26
